---
abstract: 'a simple syntax for lexical field-based objects'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  ExtUtils::CBuilder: '0'
  Test::Fatal: '0'
  Test::More: '0.88'
  Test::Refcount: '0'
configure_requires:
  Module::Build: '0.4004'
  XS::Parse::Keyword::Builder: '0.22'
  XS::Parse::Sublike::Builder: '0.15'
dynamic_config: 1
generated_by: 'Module::Build version 0.4231, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Class-Plain
provides:
  Class::Plain:
    file: lib/Class/Plain.pm
    version: '0.68'
  Class::Plain::ExtensionBuilder:
    file: lib/Class/Plain/ExtensionBuilder.pm
    version: '0.68'
  Class::Plain::MOP::Class:
    file: lib/Class/Plain/MOP/Class.pm
    version: '0.68'
  Class::Plain::MOP::Field:
    file: lib/Class/Plain/MOP/Field.pm
    version: '0.68'
  Class::Plain::MOP::FieldAttr:
    file: lib/Class/Plain/MOP/FieldAttr.pm
    version: '0.68'
  Class::Plain::MOP::Method:
    file: lib/Class/Plain/MOP/Method.pm
    version: '0.68'
  Class::Plain::MetaFunctions:
    file: lib/Class/Plain/MetaFunctions.pm
    version: '0.68'
requires:
  XS::Parse::Keyword: '0.22'
  XS::Parse::Sublike: '0.15'
  perl: '5.018'
resources:
  license: http://dev.perl.org/licenses/
version: '0.68'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
